id: P26483C80
initial_creation_type: input
source_metadata:
  title: Prajñāpāramitā (Deity) Series
  language: bo
  description: 'Texts related to the Great Mother (yum chen) Prajñāpāramitā, mother
    of all the buddhas:'
  volume:
    25335882efb742d982c05d9613d0d6ba:
      title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
      parent: Guru Yoga
    4759ef7b5c544048b3ca361fc6ee2791:
      title: A Brief Visualization and Recitation of the Great Mother Prajñāpāramitā
      parent: Sādhanas
created_at: '2022-03-01T05:13:22.916288'
last_modified_at: '2022-03-01T05:13:22.916290'
statistics:
  total_words: 800
  total_non_words: 96
quality:
  non_words_ratio: 0.12
